spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diagram
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/local
