spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust:
            enable: false

  datasource:
    url: jdbc:postgresql://localhost:5432/diagram
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/local?authSource=admin

erd:
  app:
    jwt:
      secret:
      expiration: 300000
      refresh-expiration: 2629746000
      cookie-name: erd-token
      refresh-cookie-name: erd-refresh-token