spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diagram
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/local?authSource=admin

erd:
  app:
    jwt:
      secret: 1b4e92769871538c645e4145c964173046e015f55fb706a5c49b8f0c2c183daf
      expiration: 3600000
      refresh-expiration: 2629746000
      cookie-name: erd-token
      refresh-cookie-name: erd-refresh-token