spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diagram
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/local?authSource=admin
